version: '3'

services:

  redis:
    container_name: cache
    image: redis:alpine  
    ports:
        - "6379:6379" 

  duplicatecheck:
    container_name: application     
    image: chethangowda/duplicatecheck-redis:latest
    ports: 
        - "8081:8081"
    build:         
        context: .         
        dockerfile: Dockerfile   
    depends_on:
      - redis
    healthcheck:          
        test: ["CMD", "ping", "-c","1", "192.168.99.101:8081"]
        interval: 10s
        timeout: 30s